// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#nullable enable
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SparkplugNet.Tests")]
namespace SparkplugNet.VersionB.ProtoBuf
{
    [global::ProtoBuf.ProtoContract()]
    internal partial class ProtoBufPayload : ProtobufPayloadBase
    {
        [global::ProtoBuf.ProtoMember(3, Name = @"seq", IsRequired = true)]
        public override ulong? Seq { get; set; }
    }
}
#nullable disable
#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion